apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx

    spec:
      initContainers:
      - name: init-nginx
        command: ["/scripts/setup.sh"]
        image: nginx:latest
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: html
            mountPath: /usr/share/nginx/html

      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html

      volumes:
        - name: html
          emptyDir: {}
        - name: scripts
          configMap:
            name: nginx-scripts
            defaultMode: 0555
            items:
            - key: setup.sh
              path: setup.sh
